In [1]:
import pandas as pd

import os

In [11]:
data_winners = pd.read_csv(
    os.path.join(
        "..", "data",
        "Nobel Peace Winners.csv"
    )
)

data_nominees = pd.read_csv(
    os.path.join(
        "..", "data",
        "Nobel Peace Nominees.csv"
    )
)

In [12]:
df_winners = data_winners.copy()
df_nominees = data_nominees.copy()

In [13]:
df_winners.head()

   Year                     Winner Winner_Nationality    Type  Region
0  1901          Jean Henri Dunant        Switzerland  Person  Europe
1  1901             Frédéric Passy             France  Person  Europe
2  1902              Élie Ducommun        Switzerland  Person  Europe
3  1902       Charles Albert Gobat        Switzerland  Person  Europe
4  1903  Sir William Randal Cremer                 UK  Person  Europe

In [14]:
df_nominees.head()

   Year                   Name  Nationality  Region
0  1901         Frédéric Passy       France  Europe
1  1901           Henry Dunant  Switzerland  Europe
2  1901          Élie Ducommun  Switzerland  Europe
3  1901   Charles Albert Gobat  Switzerland  Europe
4  1901  William Randal Cremer      England  Europe

In [15]:
# create decade
df_nominees["Decade"] = (df_nominees["Year"] // 10) * 10
df_winners["Decade"] = (df_winners["Year"] // 10) * 10

In [16]:
df_nominees

      Year                   Name  Nationality  Region  Decade
0     1901         Frédéric Passy       France  Europe    1900
1     1901           Henry Dunant  Switzerland  Europe    1900
2     1901          Élie Ducommun  Switzerland  Europe    1900
3     1901   Charles Albert Gobat  Switzerland  Europe    1900
4     1901  William Randal Cremer      England  Europe    1900
...    ...                    ...          ...     ...     ...
3018  2025             Hind Rajab    Palestine    Asia    2020
3019  2025         Feride Rushiti       Kosovo  Europe    2020
3020  2025      Mikola Statkevich      Belarus  Europe    2020
3021  2025                Wang Yi      Sichuan    Asia    2020
3022  2025         Daniella Weiss       Israel    Asia    2020

[3023 rows x 5 columns]

In [17]:
# count nominees by decade × region
df_nominee_region_decade = (
    df_nominees.groupby(["Decade", "Region"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

df_nominee_region_decade

Region  Decade  Africa  America  Asia  Europe  Oceania
0         1900       0       16     2     187        2
1         1910       0       42     2     190        0
2         1920       0       38     4     173        0
3         1930       3       71    24     240        3
4         1940       2       29     9      53        1
5         1950       1       76    29     148        4
6         1960       5      102    62     169        0
7         1970      15      105    39     123        1
8         1980      15       41    20      47        1
9         1990       8       37    34      32        1
10        2000      18      107    40      63        0
11        2010      48       97   105      88       10
12        2020      16       59    99      58        9

In [23]:
df_nominee_region_decade["Total"] = df_nominee_region_decade[[
    "Africa", "America", "Asia", "Europe", "Oceania"
]].sum(axis=1)

df_nominee_region_decade

Region  Decade  Africa  America  Asia  Europe  Oceania  Total
0         1900       0       16     2     187        2    207
1         1910       0       42     2     190        0    234
2         1920       0       38     4     173        0    215
3         1930       3       71    24     240        3    341
4         1940       2       29     9      53        1     94
5         1950       1       76    29     148        4    258
6         1960       5      102    62     169        0    338
7         1970      15      105    39     123        1    283
8         1980      15       41    20      47        1    124
9         1990       8       37    34      32        1    112
10        2000      18      107    40      63        0    228
11        2010      48       97   105      88       10    348
12        2020      16       59    99      58        9    241

In [24]:
df_nominee_region_decade.to_csv(
    os.path.join(
            "..", "data",
            "Nobel Peace Nominees (Decade).csv"
            ),
            index=False
)

In [19]:
# count winners by decade × region
df_winner_region_decade = (
    df_winners.groupby(["Decade", "Region"])
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

df_winner_region_decade

Region  Decade  Africa  America  Asia  Europe
0         1900       0        1     0      12
1         1910       0        2     0       3
2         1920       0        2     0       9
3         1930       0        3     0       5
4         1940       0        3     0       1
5         1950       0        3     0       4
6         1960       1        2     0       2
7         1970       1        2     4       5
8         1980       1        4     1       2
9         1990       2        2     6       4
10        2000       3        3     3       1
11        2010       4        1     5       0
12        2020       0        2     1       2

In [26]:
df_winner_region_decade["Total"] = df_winner_region_decade[[
    "Africa", "America", "Asia", "Europe"
]].sum(axis=1)

df_winner_region_decade

Region  Decade  Africa  America  Asia  Europe  Total
0         1900       0        1     0      12     13
1         1910       0        2     0       3      5
2         1920       0        2     0       9     11
3         1930       0        3     0       5      8
4         1940       0        3     0       1      4
5         1950       0        3     0       4      7
6         1960       1        2     0       2      5
7         1970       1        2     4       5     12
8         1980       1        4     1       2      8
9         1990       2        2     6       4     14
10        2000       3        3     3       1     10
11        2010       4        1     5       0     10
12        2020       0        2     1       2      5

In [27]:
df_winner_region_decade.to_csv(
    os.path.join(
            "..", "data",
            "Nobel Peace Winners (Decade).csv"
            ),
            index=False
)