In [1]:
import pandas as pd

import os

In [2]:
data_winners = pd.read_csv(
    os.path.join(
        "..", "data",
        "Nobel Peace Winners.csv"
    )
)

data_nominees = pd.read_csv(
    os.path.join(
        "..", "data",
        "Nobel Peace Nominees.csv"
    )
)

In [7]:
df_winners = data_winners.copy()
df_nominees = data_nominees.copy()

In [8]:
df_winners.head()

   Year                     Winner Winner_Nationality    Type
0  1901          Jean Henri Dunant        Switzerland  Person
1  1901             Frédéric Passy             France  Person
2  1902              Élie Ducommun        Switzerland  Person
3  1902       Charles Albert Gobat        Switzerland  Person
4  1903  Sir William Randal Cremer                 UK  Person

In [9]:
df_nominees.head()

   Year                   Name  Nationality  Region
0  1901         Frédéric Passy       France  Europe
1  1901           Henry Dunant  Switzerland  Europe
2  1901          Élie Ducommun  Switzerland  Europe
3  1901   Charles Albert Gobat  Switzerland  Europe
4  1901  William Randal Cremer      England  Europe

In [10]:
# create decade
df_nominees["Decade"] = (df_nominees["Year"] // 10) * 10

df_nominees

      Year                   Name  Nationality  Region  Decade
0     1901         Frédéric Passy       France  Europe    1900
1     1901           Henry Dunant  Switzerland  Europe    1900
2     1901          Élie Ducommun  Switzerland  Europe    1900
3     1901   Charles Albert Gobat  Switzerland  Europe    1900
4     1901  William Randal Cremer      England  Europe    1900
...    ...                    ...          ...     ...     ...
3018  2025             Hind Rajab    Palestine    Asia    2020
3019  2025         Feride Rushiti       Kosovo  Europe    2020
3020  2025      Mikola Statkevich      Belarus  Europe    2020
3021  2025                Wang Yi      Sichuan    Asia    2020
3022  2025         Daniella Weiss       Israel    Asia    2020

[3023 rows x 5 columns]